"""Filesystem helpers for deterministic safe output."""

from __future__ import annotations

import re
import shutil
from pathlib import Path

from .errors import ConfigError, PathTraversalError

_URL_SAFE_NAME_RE = re.compile(r"^[a-z0-9][a-z0-9-]*$")
_URL_SAFE_SEGMENT_RE = re.compile(r"^[a-z0-9][a-z0-9-]*$")


def ensure_url_safe_name(name: str) -> str:
    if not _URL_SAFE_NAME_RE.fullmatch(name):
        raise ConfigError(
            f"Project name '{name}' is not URL-safe. Use lowercase letters, numbers, "
            "and dashes, starting with a letter or number."
        )
    return name


def ensure_variant_segment(segment: str) -> str:
    if not segment:
        return ""
    if not _URL_SAFE_SEGMENT_RE.fullmatch(segment):
        raise ConfigError(
            "Variant url_segment values must be empty or use lowercase letters, "
            "numbers, and dashes without path separators."
        )
    return segment


def resolve_path(base_dir: Path, value: str | Path) -> Path:
    candidate = Path(value)
    if not candidate.is_absolute():
        candidate = base_dir / candidate
    return candidate.resolve()


def ensure_within_root(root: Path, candidate: Path) -> Path:
    root_resolved = root.resolve()
    candidate_resolved = candidate.resolve()
    try:
        candidate_resolved.relative_to(root_resolved)
    except ValueError as exc:  # pragma: no cover - platform-specific wording
        raise PathTraversalError(
            f"Generated path '{candidate_resolved}' escapes "
            f"configured root '{root_resolved}'."
        ) from exc
    return candidate_resolved


def docname_to_output_path(docname: str) -> Path:
    relative = Path(docname)
    if relative.is_absolute() or ".." in relative.parts:
        raise PathTraversalError(f"Unsafe Sphinx docname '{docname}'.")
    if not relative.parts:
        raise PathTraversalError("Empty Sphinx docname is not allowed.")
    return relative.with_suffix(".md")


def output_path_for(
    tools_dir: Path,
    project_name: str,
    docname: str,
    *,
    variant_segment: str = "",
) -> Path:
    parts = [tools_dir, Path(project_name)]
    if variant_segment:
        parts.append(Path(variant_segment))
    return Path(*parts) / docname_to_output_path(docname)


def permalink_for(
    tools_dir: Path,
    project_name: str,
    docname: str,
    *,
    variant_segment: str = "",
) -> str:
    parts = list(Path(docname).parts)
    if ".." in parts or not parts:
        raise PathTraversalError(f"Unsafe Sphinx docname '{docname}'.")
    base_parts = [
        segment.strip("/") for segment in tools_dir.parts if segment not in (".", "")
    ]
    permalink_parts = [*base_parts, project_name]
    if variant_segment:
        permalink_parts.append(variant_segment)
    permalink_parts.extend(parts)
    if parts[-1] == "index":
        permalink_parts = permalink_parts[:-1]
    return "/" + "/".join(permalink_parts) + "/"


def nav_key_for(project_name: str, variant_name: str, *, is_default: bool) -> str:
    return project_name if is_default else f"{project_name}-{variant_name}"


def generated_notice(comment_prefix: str = "<!--", comment_suffix: str = "-->") -> str:
    return (
        f"{comment_prefix} GENERATED by sphinxpress. "
        f"Do not edit by hand. {comment_suffix}"
    )


def write_text_if_changed(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.write_text(content, encoding="utf-8")


def reset_directory(path: Path) -> None:
    if path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True, exist_ok=True)


def copy_tree(src: Path, dst: Path) -> None:
    if dst.exists():
        shutil.rmtree(dst)
    for source_path in sorted(src.rglob("*")):
        relative = source_path.relative_to(src)
        if any(
            part in {"_build", ".doctrees", "__pycache__"} for part in relative.parts
        ):
            continue
        destination = dst / relative
        if source_path.is_dir():
            destination.mkdir(parents=True, exist_ok=True)
        else:
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source_path, destination)
