"""Build Jekyll site output from resolved Sphinx JSON pages."""

from __future__ import annotations

import json
from collections.abc import Collection
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import unquote, urlsplit

from .env_manager import prepare_build_environment
from .errors import ConfigError, SphinxBuildError
from .jekyll_writer import write_jekyll_page, write_tool_nav, write_tools_index
from .models import (
    AppConfig,
    NavEntry,
    PageRender,
    ProjectConfig,
    ReleaseMetadata,
    ResolvedSiteTarget,
    ToolSummary,
)
from .paths import (
    ensure_within_root,
    output_path_for,
    permalink_for,
    reset_directory,
)
from .release import resolve_release_metadata
from .search_index import write_search_index
from .source_manager import python_paths_for_target, resolve_site_targets
from .sphinx_runner import run_sphinx

_MANIFEST_PATH = "site-output-manifest.json"
_GENERATED_MARKER = "GENERATED by sphinxpress. Do not edit by hand."


def build_site(
    config: AppConfig,
    projects: list[ProjectConfig],
    *,
    sphinx_build: str | None = None,
    variants: list[str] | None = None,
) -> list[Path]:
    work_root = config.build.work_dir / "site"
    if not config.build.keep_build_dir:
        reset_directory(work_root)
    else:
        work_root.mkdir(parents=True, exist_ok=True)

    json_root = work_root / "json"
    doctree_root = work_root / "doctrees"
    outputs: list[Path] = []
    sphinx_build = sphinx_build or prepare_build_environment(config, projects)
    targets = resolve_site_targets(config, projects, variants=variants)
    if not targets:
        raise ConfigError("No site targets were selected for build-site.")

    targets_by_project = _targets_by_project(targets)
    release_by_project = _release_metadata_by_project(config, projects)
    previous_manifest = _load_manifest(config.build.work_dir / _MANIFEST_PATH)
    next_target_paths: dict[str, list[str]] = {}

    for target in targets:
        rendered_pages = _render_target_json(
            config,
            target,
            json_root / target.project.name / target.variant.name,
            doctree_root / target.project.name / target.variant.name,
            sphinx_build=sphinx_build,
        )
        versions = _version_catalog(
            config,
            targets_by_project[target.project.name],
            current_variant=target.variant.name,
        )
        written_paths: list[Path] = []
        for page in rendered_pages:
            written = write_jekyll_page(
                site=config.site,
                relative_path=page.output_path,
                title=page.title,
                permalink=page.permalink,
                nav_tool=page.nav_tool,
                body_html=page.body_html,
                docs_project=page.docs_project,
                docs_variant=page.docs_variant,
                docs_ref=page.docs_ref,
                docs_commit=page.docs_commit,
                search_enabled=config.site.search.enabled,
            )
            outputs.append(written)
            written_paths.append(written)

        entries = [
            NavEntry(slug=page.docname, title=page.title, url=page.permalink)
            for page in _ordered_nav_pages(target, rendered_pages)
        ]
        nav_path = write_tool_nav(
            site=config.site,
            target=target,
            release=release_by_project.get(target.project.name),
            versions=versions,
            entries=entries,
        )
        outputs.append(nav_path)
        written_paths.append(nav_path)
        search_index_path = write_search_index(
            site=config.site,
            target=target,
            pages=rendered_pages,
        )
        if search_index_path is not None:
            outputs.append(config.site.root / search_index_path)
            written_paths.append(config.site.root / search_index_path)
        next_target_paths[_target_key(target)] = [
            path.relative_to(config.site.root).as_posix() for path in written_paths
        ]

    tools_index = write_tools_index(
        site=config.site,
        relative_path=config.site.tools_dir / "index.md",
        title=config.site.title,
        tools=_tool_links(
            config,
            targets_by_project,
            release_by_project=release_by_project,
        ),
    )
    outputs.append(tools_index)
    _cleanup_stale_outputs(
        site_root=config.site.root,
        tools_dir=config.site.tools_dir,
        previous_manifest=previous_manifest,
        next_target_paths=next_target_paths,
        targets=targets,
    )
    _write_manifest(
        config.build.work_dir / _MANIFEST_PATH,
        {
            "version": 1,
            "targets": {
                **_previous_target_paths(
                    previous_manifest, exclude=next_target_paths.keys()
                ),
                **next_target_paths,
            },
            "shared": [tools_index.relative_to(config.site.root).as_posix()],
        },
    )
    return outputs


def _targets_by_project(
    targets: list[ResolvedSiteTarget],
) -> dict[str, list[ResolvedSiteTarget]]:
    grouped: dict[str, list[ResolvedSiteTarget]] = {}
    for target in targets:
        grouped.setdefault(target.project.name, []).append(target)
    return grouped


def _release_metadata_by_project(
    config: AppConfig,
    projects: list[ProjectConfig],
) -> dict[str, ReleaseMetadata]:
    metadata: dict[str, ReleaseMetadata] = {}
    for project in projects:
        if any(
            variant.source == "release"
            for variant in config.site.versioning.ordered_variants(
                project.site_variants
            )
        ):
            metadata[project.name] = resolve_release_metadata(config, project)
    return metadata


def _version_catalog(
    config: AppConfig,
    targets: list[ResolvedSiteTarget],
    *,
    current_variant: str,
) -> list[dict[str, object]]:
    return [
        {
            "name": target.variant.name,
            "label": target.variant.label,
            "ref": target.resolved_ref,
            "url": permalink_for(
                config.site.tools_dir,
                target.project.name,
                target.project.root_doc,
                variant_segment=target.variant.url_segment,
            ),
            "current": target.variant.name == current_variant,
        }
        for target in targets
    ]


def _tool_links(
    config: AppConfig,
    targets_by_project: dict[str, list[ResolvedSiteTarget]],
    *,
    release_by_project: dict[str, ReleaseMetadata],
) -> list[ToolSummary]:
    summaries: list[ToolSummary] = []
    for project in config.ordered_projects():
        project_targets = targets_by_project.get(project.name, [])
        default_target = next(
            (target for target in project_targets if target.is_default),
            None,
        )
        if default_target is not None:
            variant_segment = default_target.variant.url_segment
        else:
            variant_segment = config.site.versioning.require_variant(
                config.site.versioning.default
            ).url_segment
        docs_url = permalink_for(
            config.site.tools_dir,
            project.name,
            project.root_doc,
            variant_segment=variant_segment,
        )
        release = release_by_project.get(project.name)
        summaries.append(
            ToolSummary(
                name=project.name,
                title=project.title,
                description=project.description,
                docs_url=docs_url,
                repo_url=project.repo_url,
                release_tag=release.tag if release else None,
                release_url=release.url if release else None,
            )
        )
    return summaries


def _render_target_json(
    config: AppConfig,
    target: ResolvedSiteTarget,
    out_dir: Path,
    doctree_dir: Path,
    *,
    sphinx_build: str | None = None,
) -> list[PageRender]:
    try:
        run_sphinx(
            builder="json",
            conf_dir=target.conf_dir,
            src_dir=target.docs_root,
            out_dir=out_dir,
            doctree_dir=doctree_dir,
            fail_on_warning=config.build.fail_on_warning,
            sphinx_build=sphinx_build or config.build.sphinx_build,
            parallel=config.build.parallel,
            log_dir=config.build.log_dir,
            log_stem=f"site-{target.project.name}-{target.variant.name}-json",
            python_paths=python_paths_for_target(target),
            environment=_target_environment(target),
        )
    except SphinxBuildError as exc:
        raise SphinxBuildError(
            f"Project '{target.project.name}', variant '{target.variant.name}': {exc}"
        ) from exc
    pages: list[PageRender] = []
    for json_path in sorted(out_dir.rglob("*.fjson")):
        data = json.loads(json_path.read_text(encoding="utf-8"))
        body_html = data.get("body")
        if not isinstance(body_html, str):
            continue
        docname = json_path.relative_to(out_dir).with_suffix("").as_posix()
        if _is_jekyll_hidden_docname(docname):
            continue
        relative_page_path = output_path_for(
            config.site.tools_dir,
            target.project.name,
            docname,
            variant_segment=target.variant.url_segment,
        )
        page = PageRender(
            docname=docname,
            title=_page_title(target.project, docname, data.get("title")),
            body_html=body_html,
            output_path=ensure_within_root(
                config.site.root, config.site.root / relative_page_path
            ).relative_to(config.site.root),
            permalink=permalink_for(
                config.site.tools_dir,
                target.project.name,
                docname,
                variant_segment=target.variant.url_segment,
            ),
            nav_tool=target.nav_key,
            docs_project=target.project.name,
            docs_variant=target.variant.name,
            docs_ref=target.resolved_ref,
            docs_commit=target.commit_sha,
        )
        pages.append(page)
    return pages


def _target_environment(target: ResolvedSiteTarget) -> dict[str, str]:
    environment = {
        "SPHINXPRESS_DOCS_PROJECT": target.project.name,
        "SPHINXPRESS_DOCS_VARIANT": target.variant.name,
        "SPHINXPRESS_DOCS_REF": target.resolved_ref,
    }
    if target.commit_sha:
        environment["SPHINXPRESS_DOCS_COMMIT"] = target.commit_sha
    return environment


def _target_key(target: ResolvedSiteTarget) -> str:
    return f"{target.project.name}:{target.variant.name}"


def _target_output_root(
    site_root: Path, tools_dir: Path, target: ResolvedSiteTarget
) -> Path:
    root = site_root / tools_dir / target.project.name
    if target.variant.url_segment:
        root = root / target.variant.url_segment
    return root


def _load_manifest(path: Path) -> dict[str, object]:
    if not path.exists():
        return {"version": 1, "targets": {}, "shared": []}
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {"version": 1, "targets": {}, "shared": []}
    if not isinstance(raw, dict):
        return {"version": 1, "targets": {}, "shared": []}
    return raw


def _previous_target_paths(
    manifest: dict[str, object], *, exclude: Collection[str]
) -> dict[str, list[str]]:
    raw_targets = manifest.get("targets")
    if not isinstance(raw_targets, dict):
        return {}
    excluded = set(exclude)
    previous: dict[str, list[str]] = {}
    for key, value in raw_targets.items():
        if not isinstance(key, str) or key in excluded or not isinstance(value, list):
            continue
        if all(isinstance(item, str) for item in value):
            previous[key] = value
    return previous


def _write_manifest(path: Path, payload: dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )


def _cleanup_stale_outputs(
    *,
    site_root: Path,
    tools_dir: Path,
    previous_manifest: dict[str, object],
    next_target_paths: dict[str, list[str]],
    targets: list[ResolvedSiteTarget],
) -> None:
    previous_targets = previous_manifest.get("targets", {})
    if not isinstance(previous_targets, dict):
        return
    target_roots = {
        _target_key(target): _target_output_root(site_root, tools_dir, target)
        for target in targets
    }
    for key, new_paths in next_target_paths.items():
        old_paths = previous_targets.get(key, [])
        if not isinstance(old_paths, list):
            continue
        stale = sorted(set(old_paths) - set(new_paths))
        for relative in stale:
            path = site_root / relative
            if path.exists() and path.is_file() and _is_generated_output(path):
                path.unlink()
                if path.suffix == ".md":
                    _prune_empty_directories(path.parent, target_roots[key])


def _is_generated_output(path: Path) -> bool:
    if path.suffix == ".json":
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            return False
        return (
            isinstance(payload, dict) and payload.get("_generated_by") == "sphinxpress"
        )
    return _GENERATED_MARKER in path.read_text(encoding="utf-8")


def _prune_empty_directories(path: Path, root: Path) -> None:
    current = path
    root = root.resolve()
    while current.exists() and current.resolve() != root:
        try:
            current.rmdir()
        except OSError:
            return
        current = current.parent


def _is_jekyll_hidden_docname(docname: str) -> bool:
    return any(part.startswith("_") for part in Path(docname).parts)


def _page_title(project: ProjectConfig, docname: str, raw_title: object) -> str:
    title = (
        raw_title if isinstance(raw_title, str) and raw_title.strip() else project.title
    )
    if docname == project.root_doc and title == project.title:
        return title
    if docname == project.root_doc:
        return title
    if title.lower().startswith(project.title.lower()):
        return title
    return f"{project.title} {title}"


class _SphinxToctreeParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self._inside_stack: list[bool] = []
        self.hrefs: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        attrs_dict = {name: value or "" for name, value in attrs}
        classes = set(attrs_dict.get("class", "").split())
        inside = bool(self._inside_stack and self._inside_stack[-1]) or (
            "toctree-wrapper" in classes
        )
        self._inside_stack.append(inside)
        if inside and tag == "a":
            href = attrs_dict.get("href")
            if href:
                self.hrefs.append(href)

    def handle_endtag(self, tag: str) -> None:
        if self._inside_stack:
            self._inside_stack.pop()


def _ordered_nav_pages(
    target: ResolvedSiteTarget, rendered_pages: list[PageRender]
) -> list[PageRender]:
    pages_by_docname = {page.docname: page for page in rendered_pages}
    ordered_docnames: list[str] = []
    seen: set[str] = set()

    def append_docname(docname: str) -> None:
        if docname in pages_by_docname and docname not in seen:
            ordered_docnames.append(docname)
            seen.add(docname)

    append_docname(target.project.root_doc)

    root_page = pages_by_docname.get(target.project.root_doc)
    toctree_docnames = (
        _extract_toctree_docnames(root_page.body_html) if root_page else []
    )
    for docname in toctree_docnames:
        append_docname(docname)

    if not toctree_docnames:
        for docname in sorted(pages_by_docname):
            if not _is_sphinx_internal_docname(docname):
                append_docname(docname)

    return [pages_by_docname[docname] for docname in ordered_docnames]


def _extract_toctree_docnames(body_html: str) -> list[str]:
    parser = _SphinxToctreeParser()
    parser.feed(body_html)
    docnames: list[str] = []
    seen: set[str] = set()
    for href in parser.hrefs:
        docname = _docname_from_html_href(href)
        if docname and docname not in seen and not _is_sphinx_internal_docname(docname):
            docnames.append(docname)
            seen.add(docname)
    return docnames


def _docname_from_html_href(href: str) -> str | None:
    split = urlsplit(href)
    if split.scheme or split.netloc or not split.path:
        return None
    path = unquote(split.path)
    if path.startswith("/"):
        return None
    if path.endswith("/"):
        path = path.rstrip("/")
    if path.endswith(".html"):
        path = path[: -len(".html")]
    parts = Path(path).parts
    if not parts or ".." in parts or parts == (".",):
        return None
    return Path(*parts).as_posix()


def _is_sphinx_internal_docname(docname: str) -> bool:
    return _is_jekyll_hidden_docname(docname) or docname in {
        "genindex",
        "py-modindex",
        "search",
    }
